dist: bionic
language: generic
before_install:
- |
  echo "Checking if a CI run is needed post commit: ${TRAVIS_COMMIT_RANGE}"
  if ! git diff --name-only ${TRAVIS_COMMIT_RANGE} | grep -qvE '(\.png$)|(\.pdf$)|(\.html$)|^(LICENSE)'
  then
    echo "Only doc files were updated, not running the CI."
    exit
  fi
- sudo add-apt-repository --yes ppa:js-reynaud/kicad-5.1
- sudo apt update -y
- sudo apt install --no-install-recommends -y kicad kicad-symbols kicad-templates
  kicad-footprints inkscape
script:
- cd scripts && ./pcb2svg.sh && cd ..
before_deploy:
- git config --local user.name "PCB Gerber Exporter"
- git config --local user.email "noreply@w4xzr.xyz"
- export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
- git tag $TRAVIS_TAG
- ls
- ls Gerbers/
deploy:
  provider: releases
  api_key:
    secure: mA58s5644V0vESyFDOlaHuiZDB00NTFsanPPM6CxSGNJpU3pynGUUQqITRaXOODy3G/UEc4vF+7arHh7Rh2Bvr5tWhxQtBvrGKDdTN8SR/8oiun1gTOXP1CgmbqfmtecH8xPaYUGfMFXYJl32Kjr4kOMuE7zjdA1bAk0kPtFuyRYrAig8Sprdn08+uejTXEM5ujvA/jv1xTeJpcgbSiY8sWQyEryYpoUIpxFhWMqNOIUf1wcn2DXXB9a6aq7oFWn17IBXrrVriiP2V2Nz3QgGeQyrI4MG1KKlPdnd9zbER9/yU81n6Nw9EKTNZ0NqydcsqxJ5eImy6QiUuNTEBEzx4PRz5Sgh0yAQPN2v2zyXnUaxXvwvr8SRWl6oKxw1az2LODdGKRH/SnKfgMo8zaACOKIc0i64yVjXmNDWLETRJlqnhewuZYDntD/+yfJCfT/2A0EbK4OfkITxQznq0RI8mJGfqG5AS5aMGJeLN9ZnTP4fcHG+3kPhzSz4rys9qegAZt+8SJDvCCqpcpdW/SXgXLtNAo0rRccis1/ip2FIqZQFr67LuM6r70IIjCD7oRBFLgar0T0dmnAqPS83Cv6roF2/8DUofYWGfihBfSzmXyZMwbi2aRaCDJrpCvAJCCR/mocOLqCDG/AeDSGdo72U5OIHG5x/KO1qnbICnCcxYk=
  file: Gerbers/MNT-120_gerbers.zip
  on:
    repo: w4xzr/MNT-120
  skip_cleanup: 'true'
